name: Otomatik ZIP Acici

on:
  push:
    branches:
      - main  # Eger ana daliniz master ise burayi master yapin

jobs:
  unzip-islemi:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: ZIP Dosyasini Klasore Cikar
        run: |
          # kaynak_kodlar.zip yazan yeri kendi yuklediginiz dosya adiyla degistirin
          unzip -o kaynak_kodlar.zip
          
          # Islem bittikten sonra kalabalik etmesin diye zip dosyasini siliyoruz
          rm kaynak_kodlar.zip

      - name: Degisiklikleri Depoya Geri Yukle
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "ZIP dosyasi basariyla acildi" || exit 0
          git push origin main
          
